package com.example.mysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController                  // Indicates this is a Controller class
@RequestMapping(path = "/users") // It deals with users related request
public class UserController {
    @Autowired                   // Indicates it's a bean auto-generated by Spring
    private UserRepository userRepository;

    /**
     * Adds a new user based on passed-in query paramter, and returns
     * with the new user consent in JSON format.
     */
    @PostMapping(path = "/user")
    public @ResponseBody User addNewUser(@RequestParam String name, @RequestParam String email) {
        User user = new User();
        user.setName(name);
        user.setEmail(email);
        user.setLevel(0);
        userRepository.save(user);
        return user;
    }
}
